Repository wecode-bootcamp-korea/28-westagram-backend-2-team, pull requests merged in 2021-12, with the labels that each got.

#3 [강민성] Mission 1: Django 초기 세팅
  students/minsung/.gitignore
  students/minsung/manage.py
  students/minsung/requirements.txt
  students/minsung/westagram/__init__.py
  students/minsung/westagram/asgi.py
  students/minsung/westagram/settings.py
  students/minsung/westagram/urls.py
  students/minsung/westagram/wsgi.py
Labels: 수정 요청

#5 [장우경] Mission 1: Django 초기 세팅
  students/woogyeong/westagram/.gitignore
  students/woogyeong/westagram/manage.py
  students/woogyeong/westagram/requirements.txt
  students/woogyeong/westagram/westagram/__init__.py
  students/woogyeong/westagram/westagram/asgi.py
  students/woogyeong/westagram/westagram/settings.py
  students/woogyeong/westagram/westagram/urls.py
  students/woogyeong/westagram/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#2 [이찬영] Mission 1 : Django 초기세팅
  students/chan/requirements.txt
  students/chan/westagram/.gitignore
  students/chan/westagram/manage.py
  students/chan/westagram/westagram/__init__.py
  students/chan/westagram/westagram/asgi.py
  students/chan/westagram/westagram/settings.py
  students/chan/westagram/westagram/urls.py
  students/chan/westagram/westagram/wsgi.py
Labels: 수정 요청, 멘토 리뷰 요청

#4 [강민성] Mission 2: 모델링 (수정)
  students/minsung/users/__init__.py
  students/minsung/users/admin.py
  students/minsung/users/apps.py
  students/minsung/users/migrations/0001_initial.py
  students/minsung/users/migrations/0002_remove_user_age_user_date_of_birth_alter_user_email_and_more.py
  students/minsung/users/migrations/0003_alter_user_password.py
  students/minsung/users/migrations/0004_rename_name_user_username.py
  students/minsung/users/migrations/__init__.py
  students/minsung/users/models.py
  students/minsung/users/tests.py
  students/minsung/users/views.py
  students/minsung/westagram/settings.py
Labels: Accepted

#7 [장우경] Mission 2: 모델링
  students/woogyeong/westagram/users/__init__.py
  students/woogyeong/westagram/users/admin.py
  students/woogyeong/westagram/users/apps.py
  students/woogyeong/westagram/users/migrations/0001_initial.py
  students/woogyeong/westagram/users/migrations/0002_rename_register_date_user_created_at_user_updated_at_and_more.py
  students/woogyeong/westagram/users/migrations/__init__.py
  students/woogyeong/westagram/users/models.py
  students/woogyeong/westagram/users/tests.py
  students/woogyeong/westagram/users/urls.py
  students/woogyeong/westagram/users/views.py
  students/woogyeong/westagram/westagram/settings.py
  students/woogyeong/westagram/westagram/urls.py
Labels: Accepted

#6 [지원석] Mission 2: 모델링
  students/wonsuk/westagram/users/__init__.py
  students/wonsuk/westagram/users/admin.py
  students/wonsuk/westagram/users/apps.py
  students/wonsuk/westagram/users/migrations/__init__.py
  students/wonsuk/westagram/users/models.py
  students/wonsuk/westagram/users/tests.py
  students/wonsuk/westagram/users/views.py
Labels: Accepted

#8 [이찬영] Mission 2: 모델링
  students/chan/westagram/users/__init__.py
  students/chan/westagram/users/admin.py
  students/chan/westagram/users/apps.py
  students/chan/westagram/users/migrations/0001_initial.py
  students/chan/westagram/users/migrations/0002_rename_phon_number_user_phone_number.py
  students/chan/westagram/users/migrations/0003_alter_user_personal_site.py
  students/chan/westagram/users/migrations/0004_alter_user_business_number_alter_user_personal_site.py
  students/chan/westagram/users/migrations/0005_alter_user_phone_number.py
  students/chan/westagram/users/migrations/__init__.py
  students/chan/westagram/users/models.py
  students/chan/westagram/users/tests.py
  students/chan/westagram/users/views.py
  students/chan/westagram/westagram/settings.py
Labels: Accepted

#10 [장우경] Mission 3: 회원가입 기능 구현
  students/woogyeong/westagram/users/urls.py
  students/woogyeong/westagram/users/validators.py
  students/woogyeong/westagram/users/views.py
Labels: Accepted

#11 [강민성] Mission 3: 회원가입 기능 구현
  students/minsung/users/migrations/0005_user_created_at_user_updated_at.py
  students/minsung/users/urls.py
  students/minsung/users/views.py
  students/minsung/westagram/urls.py
Labels: Accepted

#13 [이찬영] Mission 3: 회원가입 기능 구현
  students/chan/westagram/users/migrations/0006_remove_user_business_number_and_more.py
  students/chan/westagram/users/models.py
  students/chan/westagram/users/urls.py
  students/chan/westagram/users/validators.py
  students/chan/westagram/users/views.py
  students/chan/westagram/westagram/urls.py
Labels: Accepted

#12 [지원석] Mission 3: 회원가입 기능 구현
  students/wonsuk/westagram/users/migrations/0001_initial.py
  students/wonsuk/westagram/users/urls.py
  students/wonsuk/westagram/users/validators.py
  students/wonsuk/westagram/users/views.py
  students/wonsuk/westagram/westagram/settings.py
  students/wonsuk/westagram/westagram/urls.py
Labels: Accepted

#16 [지원석] Mission 4: 로그인 기능 구현
  students/wonsuk/westagram/users/urls.py
  students/wonsuk/westagram/users/views.py
Labels: Accepted

#14 [강민성] Mission 4: 로그인 기능 구현
  students/minsung/users/urls.py
  students/minsung/users/views.py
Labels: Accepted

#17 [이찬영] Mission 4: 로그인 기능 구현
  students/chan/westagram/users/urls.py
  students/chan/westagram/users/views.py
  students/chan/westagram/westagram/settings.py
Labels: 멘토 리뷰 요청

#15 [장우경] Mission 4: 로그인 기능 구현
  students/woogyeong/westagram/users/urls.py
  students/woogyeong/westagram/users/views.py
Labels: 멘토 리뷰 요청

#22 [장우경] Mission 5: 회원가입 비밀번호 암호화 적용
  students/woogyeong/westagram/users/validators.py
  students/woogyeong/westagram/users/views.py
Labels: 멘토 리뷰 요청

#19 [이찬영] Mission 5: 회원가입 비밀번호 암호화 적용
  students/chan/westagram/users/views.py
Labels: Accepted

#18 [강민성] Mission 5: 회원가입 비밀번호 암호화 적용
  students/minsung/users/views.py
Labels: 멘토 리뷰 요청

#23 [지원석] Mission 6: 로그인 JWT 적용
  students/wonsuk/westagram/users/views.py
Labels: 멘토 리뷰 요청
